# Generated by Django 4.2.2 on 2023-07-24 23:52

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="email address"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "fotoUsuario",
                    models.FileField(
                        blank=True,
                        db_comment="Foto del Usuario",
                        null=True,
                        upload_to="usuarios/",
                    ),
                ),
                (
                    "tipoUsuario",
                    models.CharField(
                        choices=[
                            ("Cliente", "Cliente"),
                            ("Administrativo", "Administrativo"),
                        ],
                        db_comment="Nombre del Tipo de usuario",
                        default="Cliente",
                        max_length=15,
                    ),
                ),
                (
                    "fechaHoraCreacion",
                    models.DateTimeField(
                        auto_now_add=True, db_comment="Fecha y hora del registro"
                    ),
                ),
                (
                    "fechaHoraActualizacion",
                    models.DateTimeField(
                        auto_now=True, db_comment="Fecha y hora última actualización"
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "abstract": False,
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="Categorias",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "catNombre",
                    models.CharField(
                        db_comment="Nombre de la categoria", max_length=50, unique=True
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Ingredientes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombreIngrediente",
                    models.CharField(
                        db_comment="Nombre del ingrediente que se desea adicionar",
                        max_length=20,
                    ),
                ),
                (
                    "precioIngrediente",
                    models.DecimalField(
                        db_comment="Precio unitario del ingrediente",
                        decimal_places=2,
                        max_digits=15,
                    ),
                ),
                (
                    "cantidadIngrediente",
                    models.IntegerField(
                        db_comment="Cantidad del ingrediente que se adicionará"
                    ),
                ),
                (
                    "unidadMedida",
                    models.CharField(
                        db_comment="unidad de medida del ingrediente",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        db_comment="Color del ingrediente", max_length=30, null=True
                    ),
                ),
                (
                    "sabor",
                    models.CharField(
                        db_comment="tipo de sabor del ingrediente si llegase a ser necesario",
                        max_length=30,
                        null=True,
                    ),
                ),
                (
                    "descripcionIngrediente",
                    models.TextField(
                        db_comment="descripción detallada del ingrediente"
                    ),
                ),
                (
                    "fechaHoraCreacion",
                    models.DateTimeField(
                        auto_now_add=True, db_comment="Fecha y hora del registro"
                    ),
                ),
                (
                    "fechaHoraActualizacion",
                    models.DateTimeField(
                        auto_now=True, db_comment="Fecha y hora última actualización"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Administradores",
            fields=[
                (
                    "user_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "cargoAdministrador",
                    models.CharField(
                        db_comment="Cargo que ocupa el administrador a registrar",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "fechaHoraCreacionAdmin",
                    models.DateTimeField(
                        auto_now_add=True, db_comment="Fecha y hora del registro"
                    ),
                ),
                (
                    "fechaHoraActualizacionAdmin",
                    models.DateTimeField(
                        auto_now=True, db_comment="Fecha y hora última actualización"
                    ),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "abstract": False,
            },
            bases=("app_DAlbas.user",),
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="Clientes",
            fields=[
                (
                    "user_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "identificacionCliente",
                    models.CharField(
                        db_comment="Identificación del cliente, puede ser cédula o NUIP",
                        max_length=20,
                        unique=True,
                    ),
                ),
                (
                    "direccionCliente",
                    models.CharField(
                        db_comment="Dirección de residencia del cliente",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "telefonoCliente",
                    models.CharField(
                        db_comment="Número telefono del cliente",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "fechaHoraCreacionCliente",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_comment="Fecha y hora del registro del cliente",
                    ),
                ),
                (
                    "fechaHoraActualizacionCliente",
                    models.DateTimeField(
                        auto_now=True, db_comment="Fecha y hora última actualización"
                    ),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "abstract": False,
            },
            bases=("app_DAlbas.user",),
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="Productos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombreProducto",
                    models.CharField(db_comment="Nombre de producto", max_length=50),
                ),
                (
                    "precioProducto",
                    models.DecimalField(
                        db_comment="precio unitario del producto",
                        decimal_places=2,
                        max_digits=15,
                    ),
                ),
                (
                    "descripcionProducto",
                    models.TextField(
                        db_comment="Descripción de cada producto de la pasteleria"
                    ),
                ),
                (
                    "imagenProducto",
                    models.FileField(
                        blank=True,
                        db_comment="Imagen del producto",
                        null=True,
                        upload_to="productos/",
                    ),
                ),
                (
                    "fechaHoraCreacion",
                    models.DateTimeField(
                        auto_now_add=True, db_comment="Fecha y hora del registro"
                    ),
                ),
                (
                    "fechaHoraActualizacion",
                    models.DateTimeField(
                        auto_now=True, db_comment="Fecha y hora última actualización"
                    ),
                ),
                (
                    "adminProducto",
                    models.ForeignKey(
                        db_comment="Fk del usuario administrador que registra cada producto",
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "categoriaProducto",
                    models.ForeignKey(
                        db_comment="Fk de la categoria a la que pertenece el producto",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="app_DAlbas.categorias",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Pedidos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fechaPedido",
                    models.DateTimeField(
                        db_comment="Fecha en que realiza el pedido",
                        default=django.utils.timezone.now,
                    ),
                ),
                (
                    "fechaEnvioPedido",
                    models.DateField(db_comment="Fecha en la que se envia el pedido"),
                ),
                (
                    "metodoPago",
                    models.CharField(
                        choices=[
                            ("Transferencia", "Transferencia"),
                            ("Efectivo", "Efectivo"),
                        ],
                        db_comment="Metodos de pago disponibles",
                        max_length=20,
                    ),
                ),
                (
                    "valorPedido",
                    models.DecimalField(
                        db_comment="valor del pedido", decimal_places=2, max_digits=15
                    ),
                ),
                (
                    "direccionPedido",
                    models.CharField(
                        db_comment="Dirección donde se enviará el pedido", max_length=15
                    ),
                ),
                (
                    "estadoPedido",
                    models.CharField(
                        choices=[
                            ("Pendiente", "Pendiente"),
                            ("En proceso", "En proceso"),
                            ("Enviado", "Enviado"),
                            ("Entregado", "Entregado"),
                            ("Cancelado", "Cancelado"),
                        ],
                        db_comment="Estado",
                        max_length=15,
                    ),
                ),
                (
                    "fechaHoraCreacion",
                    models.DateTimeField(
                        auto_now_add=True, db_comment="Fecha y hora del registro"
                    ),
                ),
                (
                    "fechaHoraActualizacion",
                    models.DateTimeField(
                        auto_now=True, db_comment="Fecha y hora última actualización"
                    ),
                ),
                (
                    "clientePedido",
                    models.ForeignKey(
                        db_comment="Fk del cliente que realiza el pedido",
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CarritoCompras",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cantidadProducto",
                    models.IntegerField(
                        db_comment="Cantidad de productos que se el cliente comprará"
                    ),
                ),
                (
                    "costoProductos",
                    models.DecimalField(
                        db_comment="Costo acumulable de los productos que se van a pedir",
                        decimal_places=2,
                        max_digits=15,
                    ),
                ),
                (
                    "fechaHoraCreacion",
                    models.DateTimeField(
                        auto_now_add=True, db_comment="Fecha y hora del registro"
                    ),
                ),
                (
                    "fechaHoraActualizacion",
                    models.DateTimeField(
                        auto_now=True, db_comment="Fecha y hora última actualización"
                    ),
                ),
                (
                    "pedidoCompra",
                    models.ForeignKey(
                        db_comment="Fk de la tabla pedido",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="app_DAlbas.pedidos",
                    ),
                ),
                (
                    "productoCompra",
                    models.ForeignKey(
                        db_comment="Fk de la tabla productos",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="app_DAlbas.productos",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AdicionDetalle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "descripcionAdicion",
                    models.TextField(
                        db_comment="Descripción detallada de la adición que se la va a hacer al pedido"
                    ),
                ),
                (
                    "valorAdicion",
                    models.DecimalField(
                        db_comment="valor que le agregará al valor del pedio por realizar un adición extra",
                        decimal_places=2,
                        max_digits=15,
                    ),
                ),
                (
                    "fechaHoraCreacion",
                    models.DateTimeField(
                        auto_now_add=True, db_comment="Fecha y hora del registro"
                    ),
                ),
                (
                    "fechaHoraActualizacion",
                    models.DateTimeField(
                        auto_now=True, db_comment="Fecha y hora última actualización"
                    ),
                ),
                (
                    "ingredienteAdicion",
                    models.ForeignKey(
                        db_comment="Fk de la tabla ingredientes",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="app_DAlbas.ingredientes",
                    ),
                ),
                (
                    "pedidoAdicion",
                    models.ForeignKey(
                        db_comment="Fk del pedido al que se le hará la adición",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="app_DAlbas.pedidos",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Abonos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fotoComprobanteAbono",
                    models.FileField(
                        blank=True,
                        db_comment="Foto del comprobante de pago del primer abono del pedido",
                        null=True,
                        upload_to="abonos/",
                    ),
                ),
                (
                    "codigoComprobanteAbono",
                    models.CharField(
                        db_comment="Código del comprobante del pago del primer abono",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "valorAbono",
                    models.DecimalField(
                        db_comment="Valor de pago del primer abono cincuenta porciento del valor del pedido",
                        decimal_places=2,
                        max_digits=15,
                    ),
                ),
                (
                    "fechaHoraCreacion",
                    models.DateTimeField(
                        auto_now_add=True, db_comment="Fecha y hora del registro"
                    ),
                ),
                (
                    "fechaHoraActualizacion",
                    models.DateTimeField(
                        auto_now=True, db_comment="Fecha y hora última actualización"
                    ),
                ),
                (
                    "pedidoAbono",
                    models.ForeignKey(
                        db_comment="Fk de la tabla pedidos",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="app_DAlbas.pedidos",
                    ),
                ),
            ],
        ),
    ]
