# Generated by Django 4.2.2 on 2023-08-01 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_DAlbas", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Comentarios",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "contenidoComentario",
                    models.TextField(db_comment="Contenido del comentario"),
                ),
                (
                    "fechaHoraCreacion",
                    models.DateTimeField(
                        auto_now_add=True, db_comment="Fecha y hora del registro"
                    ),
                ),
                (
                    "fechaHoraActualizacion",
                    models.DateTimeField(
                        auto_now=True, db_comment="Fecha y hora última actualización"
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="productos",
            name="adminProducto",
        ),
    ]
