# Generated by Django 4.2.2 on 2023-08-01 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app_DAlbas", "0002_comentarios_remove_productos_adminproducto"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="clientes",
            name="user_ptr",
        ),
        migrations.DeleteModel(
            name="Administradores",
        ),
        migrations.DeleteModel(
            name="Clientes",
        ),
    ]
