# Generated by Django 4.2.2 on 2023-08-01 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_DAlbas", "0003_remove_clientes_user_ptr_delete_administradores_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Administradores",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cargoAdministrador",
                    models.CharField(
                        db_comment="Cargo que ocupa el administrador a registrar",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "fechaHoraCreacionAdmin",
                    models.DateTimeField(
                        auto_now_add=True, db_comment="Fecha y hora del registro"
                    ),
                ),
                (
                    "fechaHoraActualizacionAdmin",
                    models.DateTimeField(
                        auto_now=True, db_comment="Fecha y hora última actualización"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Clientes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "identificacionCliente",
                    models.CharField(
                        db_comment="Identificación del cliente, puede ser cédula o NUIP",
                        max_length=20,
                        unique=True,
                    ),
                ),
                (
                    "direccionCliente",
                    models.CharField(
                        db_comment="Dirección de residencia del cliente",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "telefonoCliente",
                    models.CharField(
                        db_comment="Número telefono del cliente",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "fechaHoraCreacionCliente",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_comment="Fecha y hora del registro del cliente",
                    ),
                ),
                (
                    "fechaHoraActualizacionCliente",
                    models.DateTimeField(
                        auto_now=True, db_comment="Fecha y hora última actualización"
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="pedidos",
            name="clientePedido",
        ),
    ]
