# Generated by Django 4.2.2 on 2023-08-01 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app_DAlbas", "0004_administradores_clientes_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Administradores",
        ),
        migrations.DeleteModel(
            name="Clientes",
        ),
    ]
